### ISSUE TITLE
Add new PUT route to associate payables with 0 ... n milestones

### ISSUE THREAD

**Issue by jkalderonkiros** [kountable/angular-kountable#45]
## Issue Workflow

- [x] Issue ready for Project Manager Review by @eolexe @damengilland
- [ ] Issue ready for Estimation
- [ ] Issue ready for Prioritization & Approval by @jefftulsa

## User Story

As a developer, I need to have access to new api endpoint, in order to associate payables and milestones.

## Steps to Reproduce / Test

As a (PERSONA / SPECIFIC USER) on (DEVICE / BROWSER) follow these steps... 

1. None identified at this time.

## Acceptance Criteria / Expected Behavior

* ...

## Special Testing Needs

- [x] None identified at this time.

## Dependencies

- [x] None identified at this time.

## Other Notes / Files

# Proposed Task

- [ ] ...

**Comment by jkalderonkiros** [comment]
Reference:
https://github.com/kountable/web-backend/issues/246
